### ISSUE TITLE
Cannot read property 'total_time_spent' of undefined

### ISSUE THREAD

**Issue by benchti** [kriskbx/gitlab-time-tracker#34]
Hello, i get this error on version 1.7.0 ( with docker) 

seems related to #27 . 
  
```
ben@ben-ant:~$ gtt -V
1.7.0

ben@ben-ant:~$ gtt report --from="2017-01-01" --to="2017-11-11"
 Warning: Merge Requests are included in the report but not queried. 
🔍  Selected projects: xxx/xxx
🔍  Resolving "xxxx/xxx"... ✓
📦  Fetching issues... ✓
📎  Merging reports... ✓
⚙️️  Processing issues... ✗91) [----------------------------------------] 0% - 0m left
Error: could not process issues.
TypeError: Cannot read property 'total_time_spent' of undefined
    at resolve (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:114:52)
    at Promise (<anonymous>)
    at promise.then (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:107:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kriskbx** [comment]
Can you post your configuration here (without the token ofc)?

**Comment by benchti** [comment]
I just check on another machine. 

I was in gtt 1.6.10 ( i think). `gtt report my/project` give me the report .
 
I did an upgrade to latest gtt `docker pull kriskbx/gitlab-time-tracker` 

And the same error appear  : 

```
ben@ben-Folio:~$ gtt report --verbose  my/project 
🔍  Selected projects:  my/project 
🔍  Resolving " my/project "... ✓
📦  Fetching issues... ✓
📦  Fetching merge requests... ✓
📎  Merging reports... ✓
⚙️️  Processing issues... ✗91) [----------------------------------------] 0% - 0m left
Error: could not process issues.
TypeError: Cannot read property 'total_time_spent' of undefined
    at resolve (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:114:52)
    at Promise (<anonymous>)
    at promise.then (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:107:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

He is my config file 

```
cat .gtt/config.yml
url: https://gitlab.mydomain.com/api/v4
token: zorglub
issueColumns:
- iid
- title
- spent
report: 
- stats
- issues 
- records
```

Thanks

**Comment by kriskbx** [comment]
Unfortunately I'm not able to replicate your issue. But I pushed a small fix to the master branch that could possibly solve it. Can you pull the master and try again?

**Comment by kriskbx** [comment]
Feel free to reopen this issue if you still encounter this error.

**Comment by benchti** [comment]
Thnaks @kriskbx  i will test in the next release ( I use docker and didn't figure out how to test the trunk) . I switch back to 1.6.10 for the moment

**Comment by kriskbx** [comment]
Thanks for your patience. I just release version `1.7.1` which should fix this error. (Sorry, I can't reproduce it, that's why I have to guess here)

Please update and reopen the issue if you still have problems with it.
