### ISSUE TITLE
Error: could not process issues.

### ISSUE THREAD

**Issue by sils** [kriskbx/gitlab-time-tracker#60]
```
sils@lsnmb ~ % gtt report group_name --type=group --this_month --verbose
...
⚙️️  Processing issues... ✗9) [====------------------------------------] 10% - <1m left
Error: could not process issues.
RangeError: Invalid array length
    at Number.padLeft (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/time.js:13:12)
    at Function.toHumanReadable (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/time.js:125:37)
    at resolve (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:130:41)
    at new Promise (<anonymous>)
    at promise.then (/usr/local/share/.config/yarn/global/node_modules/gitlab-time-tracker/src/models/hasTimes.js:110:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

@kriskbx let me know if there's other information that can help.

**Comment by sils** [comment]
FWIW this only appears if I include closed issues as well and not just opened. Once I remove `closed: true` from my config this disappears, probably this is related to one of our closed issues?

**Comment by sils** [comment]
`console.log(inserts, inserts.days);` in `toHumanReadable` gives:

```
{ sign: '-',
  days_overall: Infinity,
  days_overall_comma: 'Infinity',
  days: Infinity } Infinity
```

just before the crash

**Comment by sils** [comment]
`times.unshift(new Time(Time.toHumanReadable(difference, null, this.config.get('hoursPerDay')), note, this, this.config));`

seems to give a `null` and way too many arguments, removing that null makes it work ^^

**Comment by sils** [comment]
@kriskbx any idea ^ ?

**Comment by kriskbx** [comment]
Sorry you guys had to wait for so long, I was busy learning for my exams, but I'm back now! Thanks for pointing this out. Will be fixed in the next release which will be released within the next 24 hours. <3
