### ISSUE TITLE
Can't run commands (beyond `--help`) on Windows in either Git Bash or Command Prompt windows

### ISSUE THREAD

**Issue by kenny-evitt** [kriskbx/gitlab-time-tracker#75]
I downloaded the *gtt-win.exe* file for version 1.7.31 from the Releases page:

 - [Release 1.7.31 · kriskbx/gitlab-time-tracker](https://github.com/kriskbx/gitlab-time-tracker/releases/tag/1.7.31)

I copied the executable to a directory in my path (for both Git Bash and Command Prompt) and created a second copy so that there are two copies, one named *gtt* and the other *gtt.exe*.

What I'm seeing in Git Bash:

```bash
kevitt@KEVITT-P3620 MINGW64 ~
$ gtt --help

  Usage: gtt [options] [command]

  Options:

    -V, --version             output the version number
    -h, --help                output usage information

  Commands:

    start [project] [id]      start monitoring time for the given project and resource id
    create [project] [title]  start monitoring time for the given project and create a new issue or merge request with the given title
    status                    shows if time monitoring is running
    stop                      stop monitoring time
    resume [project]          resume monitoring time for last stopped record
    cancel                    cancel and discard active monitoring time
    log                       log recorded time records
    sync                      sync local time records to GitLab
    edit [id]                 edit time record by the given id
    delete [id]               delete time record by the given id
    report [project] [ids]    generate a report for the given project and issues
    config                    edit the configuration file in your default editor
    help [cmd]                display help for [cmd]

kevitt@KEVITT-P3620 MINGW64 ~
$ gtt help config

kevitt@KEVITT-P3620 MINGW64 ~
$ gtt config

```

What I'm seeing in Command Prompt:

```
I:\>gtt --help

  Usage: gtt [options] [command]

  Options:

    -V, --version             output the version number
    -h, --help                output usage information

  Commands:

    start [project] [id]      start monitoring time for the given project and resource id
    create [project] [title]  start monitoring time for the given project and create a new issue or merge request with the given title
    status                    shows if time monitoring is running
    stop                      stop monitoring time
    resume [project]          resume monitoring time for last stopped record
    cancel                    cancel and discard active monitoring time
    log                       log recorded time records
    sync                      sync local time records to GitLab
    edit [id]                 edit time record by the given id
    delete [id]               delete time record by the given id
    report [project] [ids]    generate a report for the given project and issues
    config                    edit the configuration file in your default editor
    help [cmd]                display help for [cmd]

I:\>gtt help config
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module 'gtt-config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

```

**Comment by pokerazor** [comment]
It's the same for the linux binary. The output is always 
```
gtt-status(1) does not exist, try --help
```
(depending of course on the subcommand)
I also tried the 1.7.30 release and tried to `ln -s gtt gtt-status` - to no avail

**Comment by hiulit** [comment]
Same here, on a Mac:

```
error: gtt-config(1) does not exist, try --help
```

**Comment by hiulit** [comment]
Is the new version publish yo `yarn`?

I tried installing it again using `yarn global add gitlab-time-tracker --prefix /usr/local` and the error still shows.

**Comment by kriskbx** [comment]
It is fixed in 1.7.34.

**Comment by hiulit** [comment]
I just installed `1.7.34` and I get the same error
```
$ gtt config
error: gtt-config(1) does not exist, try --help
```
on Mac (10.4.2)

**Comment by kriskbx** [comment]
Can you paste the output of these commands here?
```
node --version
yarn --version
gtt --version
```

**Comment by hiulit** [comment]
BTW, where can I find config file in a Mac?

I tried looking at `~/.local/share/.gtt` but the folder doesn't exists there.
I also tried `~/.gtt` with no luck either.

Could this be related to error message above?

**Comment by hiulit** [comment]
Of course! No problem.

Here you go:

```
$ node --version
v10.4.1
$ yarn --version
1.13.0
$ gtt --version
1.7.34
```

**Comment by kriskbx** [comment]
I just pushed version 1.7.35. Can remove gtt and try again?

**Comment by hiulit** [comment]
Nice! It's seems to be working on `1.7.35` 🎉 

I typed the command `gtt config` and it opened a `config.yml`.
